In [1]:
import tensorflow as tf
from working_memory_model import WorkingMemoryModel
import random
from tensorflow.keras import activations, losses
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
tf.test.is_built_with_gpu_support()

True

In [3]:
from model_test_functions import training_loop_association, make_association_game

In [4]:
model = WorkingMemoryModel([8, 16, 32, 32, 16, 5], learning_rate=0.0002, do_initial_relu=False, do_final_sigmoid=True, do_hebbian_learning=True)

In [5]:
print_sep = 10

model.update_learning_rate(0.0005)
iters = 10000
loss = 0
for i in range(iters):
    gap_length = random.randrange(6, 9)
    loss += float(training_loop_association(model, 5, 2, gap_length=gap_length))
    if (i+1) % print_sep == 0:
        print(1, i, loss/print_sep)
        loss = 0
model.save_weights("checkpoints/testa1_checkpoint.ckpt")





1 9 0.25013350546360014
1 19 0.24822341352701188
1 29 0.245860356092453
1 39 0.2437646433711052
1 49 0.24197340607643128
1 59 0.24037844836711883
1 69 0.2391117677092552
1 79 0.23817755579948424
1 89 0.2369950756430626
1 99 0.2358149990439415
1 109 0.23470703661441802
1 119 0.23399877846240996
1 129 0.23271337002515793
1 139 0.23170754909515381
1 149 0.2313839986920357
1 159 0.23041541427373885
1 169 0.22962595671415328
1 179 0.229337278008461
1 189 0.22836621403694152
1 199 0.22804846614599228
1 209 0.2274016782641411
1 219 0.22684061378240586
1 229 0.22656091153621674
1 239 0.22600449919700621
1 249 0.22537734508514404
1 259 0.2250143975019455
1 269 0.224943707883358
1 279 0.22438709288835526
1 289 0.22452070116996764
1 299 0.22421777993440628
1 309 0.22413208186626435
1 319 0.2240089774131775
1 329 0.22358706444501877
1 339 0.2230615124106407
1 349 0.22336904257535933
1 359 0.22262270897626876
1 369 0.22324612140655517
1 379 0.22333269864320754
1 389 0.2224091187119484
1 399 0.22142

In [6]:
print_sep = 10

model.update_learning_rate(0.0002)
iters = 20000
loss = 0
for i in range(iters):
    gap_length = random.randrange(8, 13)
    loss += float(training_loop_association(model, 5, 2, gap_length=gap_length))
    if (i+1) % print_sep == 0:
        print(2, i, loss/print_sep)
        loss = 0
model.save_weights("checkpoints/testa2_checkpoint.ckpt")

2 9 0.18235669136047364
2 19 0.1760168731212616
2 29 0.17142877131700515
2 39 0.15863094329833985
2 49 0.16506779342889785
2 59 0.17046770453453064
2 69 0.1651434823870659
2 79 0.16289177983999253
2 89 0.16924117952585221
2 99 0.16485441774129866
2 109 0.16154578775167466
2 119 0.16199054718017578
2 129 0.15719817578792572
2 139 0.15117320269346238
2 149 0.15846168398857116
2 159 0.16130535006523133
2 169 0.16031993478536605
2 179 0.16253658682107924
2 189 0.15780274868011473
2 199 0.15809749066829681
2 209 0.1583138331770897
2 219 0.15440704822540283
2 229 0.15354293584823608
2 239 0.15229883491992952
2 249 0.16078801602125167
2 259 0.16078601628541947
2 269 0.15758247971534728
2 279 0.15741403251886368
2 289 0.15687382817268372
2 299 0.15282263308763505
2 309 0.15583284497261046
2 319 0.1550753891468048
2 329 0.15154621750116348
2 339 0.1575614795088768
2 349 0.15763894319534302
2 359 0.15121344923973085
2 369 0.15487212538719178
2 379 0.1565440684556961
2 389 0.1452426418662071
2 39

In [7]:
print_sep = 10

model.update_learning_rate(0.0001)
iters = 50000
loss = 0
for i in range(iters):
    gap_length = random.randrange(12, 19)
    loss += float(training_loop_association(model, 5, 2, gap_length=gap_length))
    if (i+1) % print_sep == 0:
        print(3, i, loss/print_sep)
        loss = 0
model.save_weights("checkpoints/testa3_checkpoint.ckpt")

3 9 0.1466020956635475
3 19 0.13773006871342658
3 29 0.12929595038294792
3 39 0.126560328155756
3 49 0.13293477520346642
3 59 0.13067061454057693
3 69 0.13007406666874885
3 79 0.13200948163866996
3 89 0.1262959845364094
3 99 0.1384276643395424
3 109 0.12948238626122474
3 119 0.11510207802057267
3 129 0.12969795987010002
3 139 0.11946248263120651
3 149 0.12360749393701553
3 159 0.13634411990642548
3 169 0.1345237076282501
3 179 0.12362180948257447
3 189 0.1303497761487961
3 199 0.13170570880174637
3 209 0.11570503711700439
3 219 0.13205748274922371
3 229 0.1326215460896492
3 239 0.12000911086797714
3 249 0.12939833402633666
3 259 0.1283298723399639
3 269 0.13567136824131013
3 279 0.1293000139296055
3 289 0.13243651911616325
3 299 0.12658818662166596
3 309 0.12349152192473412
3 319 0.13508116602897643
3 329 0.12445587366819381
3 339 0.1255939319729805
3 349 0.12539517432451247
3 359 0.12245853990316391
3 369 0.12404723763465882
3 379 0.12768129333853723
3 389 0.12788544595241547
3 399 0.

In [10]:
model.reset_memory()
print(training_loop_association(model, 5, 2, gap_length=16, do_print=True))

tf.Tensor(
[[0.95 0.05 0.  ]
 [0.44 0.15 0.02]
 [0.88 0.01 0.02]
 [0.01 0.68 0.07]
 [0.99 0.01 0.02]
 [0.98 0.   0.6 ]
 [0.98 0.01 0.09]
 [0.97 0.01 0.02]
 [0.05 0.75 0.22]
 [0.01 0.91 0.39]
 [0.01 0.96 0.17]
 [0.01 0.92 0.26]
 [0.   0.95 0.18]
 [0.   0.95 0.23]
 [0.   0.95 0.22]
 [0.   0.95 0.22]
 [0.06 0.   0.18]
 [0.17 0.05 0.76]
 [0.05 0.05 0.52]
 [0.06 0.05 0.6 ]
 [0.04 0.31 0.55]
 [0.   0.39 0.51]
 [0.02 0.38 0.48]
 [0.07 0.27 0.46]
 [0.87 0.   0.37]
 [0.66 0.   0.41]
 [0.94 0.   0.15]
 [0.96 0.   0.15]
 [0.91 0.09 0.09]
 [0.92 0.09 0.09]
 [0.92 0.09 0.09]
 [0.92 0.09 0.1 ]
 [0.02 0.76 0.03]
 [0.   1.   0.52]
 [0.01 0.92 0.21]
 [0.01 0.93 0.33]
 [0.   0.94 0.44]
 [0.01 0.94 0.37]
 [0.   0.95 0.38]
 [0.   0.95 0.41]
 [0.12 0.39 0.7 ]
 [0.02 0.05 0.92]
 [0.14 0.12 0.76]
 [0.13 0.09 0.78]
 [0.19 0.06 0.79]
 [0.29 0.04 0.75]
 [0.39 0.03 0.7 ]
 [0.48 0.03 0.64]
 [0.27 0.   0.79]
 [0.69 0.09 0.32]
 [0.71 0.03 0.32]
 [0.81 0.02 0.24]
 [0.84 0.02 0.17]
 [0.86 0.02 0.16]
 [0.87 0.02 0.17]